model:
  # ViT Parameters
  image_size: 32
  patch_size: 4
  num_classes: 10
  dim: 256
  depth: 6
  heads: 8
  mlp_dim: 512
  channels: 3
  dropout: 0.1
  
  # Positional Encoding Configuration
  positional_encoding:
    type: "2d_sincos"  # Options: "2d_sincos", "2d_rope", "stft", "wavelets"
    mode: "add"  # Options: "add", "concat" (concat not applicable for 2d_rope)
    pos_dim: 64  # Only used when mode is "concat"
    proj_dim: 192  # Only used when mode is "concat" (dim - pos_dim)
    
    # STFT-specific parameters
    stft:
      window_size: 16
      hop_length: 8
      n_fft: 32
    
    # Wavelet-specific parameters
    wavelets:
      wavelet_type: "db4"  # daubechies-4
      levels: 3

data:
  # Data parameters
  dataset: "cifar10"
  batch_size: 128
  num_workers: 4
  
  # Data augmentation
  augmentation:
    random_crop: false
    random_horizontal_flip: true
    rand_augment: true
    rand_augment_num_ops: 2
    rand_augment_magnitude: 9
    normalize: true
    
  # Normalization parameters for CIFAR-10
  normalize_mean: [0.4914, 0.4822, 0.4465]
  normalize_std: [0.2023, 0.1994, 0.2010]

training:
  # Training parameters
  num_epochs: 100
  learning_rate: 3e-4
  weight_decay: 1e-4
  optimizer: "adamw"
  scheduler: "cosine"
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.0001
  
  # Checkpointing
  checkpoint_dir: "checkpoints"
  save_every_n_epochs: 5
  save_best_model: true
  
  # Logging
  log_dir: "logs"
  log_every_n_steps: 100

testing:
  # Model loading
  checkpoint_path: "checkpoints/best_model.pth"
  
  # Attack configuration
  attacks:
    - name: "phase_weak"
      type: "phase"
      epsilon: 0.1
      frequency_radius: 0.1
      num_pixels: 100
      noise_std: 0.05
      
    - name: "phase_strong"
      type: "phase"
      epsilon: 0.5
      frequency_radius: 0.1
      num_pixels: 100
      noise_std: 0.05
      
    - name: "magnitude_weak"
      type: "magnitude"
      epsilon: 0.1
      frequency_radius: 0.1
      num_pixels: 100
      noise_std: 0.05
      
    - name: "magnitude_strong"
      type: "magnitude"
      epsilon: 0.5
      frequency_radius: 0.1
      num_pixels: 100
      noise_std: 0.05
      
    - name: "normal_weak"
      type: "normal"
      epsilon: 0.1
      frequency_radius: 0.1
      num_pixels: 100
      noise_std: 0.05
      
    - name: "normal_strong"
      type: "normal"
      epsilon: 0.1
      frequency_radius: 0.1
      num_pixels: 100
      noise_std: 0.2
      
    - name: "low_freq"
      type: "low_freq"
      epsilon: 0.2
      frequency_radius: 0.3
      num_pixels: 100
      noise_std: 0.05
      
    - name: "high_freq"
      type: "high_freq"
      epsilon: 0.2
      frequency_radius: 0.3
      num_pixels: 100
      noise_std: 0.05
      
    # - name: "pixel_attack"
    #   type: "pixel"
    #   epsilon: 0.5
    #   frequency_radius: 0.1
    #   num_pixels: 1000
    #   noise_std: 0.05
  
  # Output configuration
  output_dir: "results"
  save_plots: true
  save_adversarial_examples: true
  
# Experiment configuration
experiment:
  name: "vit_pe_experiment"
  description: "Adversarial attacks on ViT with different positional encodings"
  seed: 42
  device: "cuda"